version: '3.3'
services:
#  nginx:
#    build: ./nginx
#    ports:
#      - '80:80'
#      - '443:443'
  mongo:
    image: mongo:6.0.4
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '127.0.0.1:5000:5000'
    environment:
      DOCKER: 1 # Environment variable for Vlad
      WAIT_HOSTS: mongo:27017
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
    - '127.0.0.1:3000:3000'
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - WDS_SOCKET_PORT=0
