version: '3.3'
services:
  mongo:
    image: mongo:6.0.4
    ports:
      - '27017:27017'
  app:
    build: .
    environment:
      DOCKER: 1 # Environment variable for Vlad
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8000'
