version: '3.3'
services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - frontend
  mongo:
    image: mongo:6.0.4
    ports:
      - '27017:27017' # MUST BE REMOVED!!!!
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DOCKER: 1 # Environment variable for Vlad
      WAIT_HOSTS: mongo:27017
    depends_on:
      - mongo
    ports:
      - '5000:5000'  # MUST BE REMOVED!!!!
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    depends_on:
      - backend
    ports:
      - '3000:3000'