version: '3.3'
services:
  mongo:
    image: mongo:6.0.4
    ports:
      - '27017:27017' # MUST BE REMOVED!!!!
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DOCKER: 1 # Environment variable for Vlad
      WAIT_HOSTS: mongo:27017
    ports:
      - '5000:5000'  # MUST BE REMOVED!!!!

      
#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile.frontend
#    ports:
#      - '3000:3000'